#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mpi.h>
#include <omp.h>


void parallel_write_MPI(void* grid, int maxval, char* filename, int k, int my_rows_number, MPI_Comm comm) {
    
    int rank, size;
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &size);
    MPI_Status status;

    MPI_File file;
    MPI_File_open(comm, filename, MPI_MODE_CREATE | MPI_MODE_WRONLY, MPI_INFO_NULL, &file);

    if (rank==0){
        char buffer[100];
        //Format the data as a string in memory, then write the string to the file using MPI_File_write
        //sprintf returns the number of characters written to the string
        int length = sprintf(buffer, "P5\n# generated by\n# Alessi Michele and Carollo Marco\n%d %d\n%d\n", k, k, maxval);

        MPI_File_write(file, buffer, length, MPI_CHAR, &status);
        
    }
    // First, get the current position of the file pointer
    MPI_Offset current_position;
    MPI_File_get_position(file, &current_position);

    // Now broadcast this position  (from the rank 0) to all other processes
    MPI_Bcast(&current_position, 1, MPI_INT, 0, MPI_COMM_WORLD);

    //let's calculate the offset, first we need an array with the number of rows for each process
    int* rows_per_process = (int*)malloc(size*sizeof(int));
    for (int i=0; i<size; i++){
        rows_per_process[i] = (i<(k%size)) ? k/size +1 : k/size;
    }
    int* offset_arr = (int*)malloc(size*sizeof(int));
    offset_arr[0] = 0;
    for (int i=1; i<size; i++){
        offset_arr[i] = offset_arr[i-1] + rows_per_process[i-1]*k;
    }
    free(rows_per_process);

    MPI_Offset offset = offset_arr[rank]*sizeof(char);

    MPI_File_seek(file, offset, MPI_SEEK_SET);

    MPI_File_write(file, grid, my_rows_number * k, MPI_CHAR, &status);

    MPI_File_close(&file);
    free(offset_arr);
    return;
}
